"""IAM entities and Core Platform reference data.

Creates the reference/lookup tables (voltage_level, region, state,
grid_owner, operational_status — docs/architecture/substation-registry.md
§6) and the IAM module's owned tables (user, user_credential, role,
permission, role_permission, user_role, external_identity_mapping,
iam_audit_log — docs/architecture/iam-module.md §11), per
docs/architecture/implementation-plan.md Phase 1.

Hand-written and manually reviewed, not machine-autogenerated: no live
PostgreSQL instance was reachable to run `alembic revision --autogenerate`
against in the environment this migration was authored in (no Docker, no
local PostgreSQL install — see Phase 1's final report). The schema below was
authored directly from the SQLAlchemy models in app/modules/iam/models.py
and app/reference_data/models.py and should still be reviewed against a real
PostgreSQL run of `alembic upgrade head` before being treated as final.

Revision ID: 0002_iam_and_core_reference_data
Revises: 0001_initial_baseline
Create Date: 2026-07-02
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_iam_and_core_reference_data"
down_revision: Union[str, None] = "0001_initial_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reference table primary keys: SMALLINT on PostgreSQL (substation-registry.md
# §6), plain INTEGER elsewhere. SQLite only grants its rowid-autoincrement
# behaviour to a column literally typed INTEGER PRIMARY KEY, not SMALLINT —
# this variant keeps the migration testable against SQLite while preserving
# the exact PostgreSQL column type. Mirrors app/reference_data/models.py.
_ReferenceKey = sa.Integer().with_variant(sa.SmallInteger(), "postgresql")


def upgrade() -> None:
    # --- Core Platform reference data (substation-registry.md §6) -----------
    op.create_table(
        "voltage_level",
        sa.Column("voltage_level_id", _ReferenceKey, autoincrement=True, nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("nominal_kv", sa.Numeric(6, 2), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("voltage_level_id"),
        sa.UniqueConstraint("label"),
    )

    op.create_table(
        "region",
        sa.Column("region_id", _ReferenceKey, autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("region_id"),
        sa.UniqueConstraint("code"),
    )

    op.create_table(
        "state",
        sa.Column("state_id", _ReferenceKey, autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("state_id"),
        sa.UniqueConstraint("code"),
    )

    op.create_table(
        "grid_owner",
        sa.Column("grid_owner_id", _ReferenceKey, autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("grid_owner_id"),
        sa.UniqueConstraint("code"),
    )

    op.create_table(
        "operational_status",
        sa.Column("operational_status_id", _ReferenceKey, autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("is_terminal", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.PrimaryKeyConstraint("operational_status_id"),
        sa.UniqueConstraint("code"),
    )

    # --- IAM (iam-module.md §11) ---------------------------------------------
    op.create_table(
        "user",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "deactivated", name="user_status", native_enum=False),
            nullable=False,
            server_default="active",
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("username"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index("uq_user_username_ci", "user", [sa.text("lower(username)")], unique=True)

    op.create_table(
        "user_credential",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("hash_algorithm", sa.String(length=50), nullable=False),
        sa.Column(
            "last_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )

    op.create_table(
        "role",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system_role", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "status",
            sa.Enum("active", "retired", name="role_status", native_enum=False),
            nullable=False,
            server_default="active",
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("name"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )

    op.create_table(
        "permission",
        sa.Column("permission_id", sa.String(length=150), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("module_scope", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("permission_id"),
    )

    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.String(length=150), nullable=False),
        sa.Column(
            "granted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
        sa.ForeignKeyConstraint(["role_id"], ["role.role_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permission.permission_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["granted_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )

    op.create_table(
        "user_role",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "granted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["role_id"], ["role.role_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["granted_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "uq_user_role_active",
        "user_role",
        ["user_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
        sqlite_where=sa.text("revoked_at IS NULL"),
    )

    op.create_table(
        "external_identity_mapping",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("external_principal_id", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column(
            "linked_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("unlinked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("linked_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["linked_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "uq_external_identity_active",
        "external_identity_mapping",
        ["external_principal_id", "provider"],
        unique=True,
        postgresql_where=sa.text("unlinked_at IS NULL"),
        sqlite_where=sa.text("unlinked_at IS NULL"),
    )

    op.create_table(
        "iam_audit_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=150), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )


def downgrade() -> None:
    op.drop_table("iam_audit_log")
    op.drop_index("uq_external_identity_active", table_name="external_identity_mapping")
    op.drop_table("external_identity_mapping")
    op.drop_index("uq_user_role_active", table_name="user_role")
    op.drop_table("user_role")
    op.drop_table("role_permission")
    op.drop_table("permission")
    op.drop_table("role")
    op.drop_table("user_credential")
    op.drop_index("uq_user_username_ci", table_name="user")
    op.drop_table("user")
    op.drop_table("operational_status")
    op.drop_table("grid_owner")
    op.drop_table("state")
    op.drop_table("region")
    op.drop_table("voltage_level")
