"""Substation Registry: substation, substation_alias, substation_audit_log.

Per docs/architecture/substation-registry.md §6 and
docs/architecture/implementation-plan.md Phase 2.

Hand-written and manually reviewed, not machine-autogenerated: no live
PostgreSQL instance was reachable to run `alembic revision --autogenerate`
against in the environment this migration was authored in (no Docker, no
local PostgreSQL install — see Phase 2's final report). The schema below was
authored directly from app/modules/substation_registry/models.py and should
still be reviewed against a real PostgreSQL run of `alembic upgrade head`
before being treated as final.

Deviation from substation-registry.md §6, documented here and in
app/modules/substation_registry/models.py: `substation_alias.substation_id`
uses `ON DELETE RESTRICT` rather than the architecture document's literal
`ON DELETE CASCADE`, per CLAUDE.md F1's standards-precedence rule (CLAUDE.md
§11.7 prohibits cascade delete on engineering entities; CLAUDE.md standards
outrank module architecture documents). This has no observable effect on
Phase 2's actual behaviour, since no hard-delete endpoint exists yet.

Revision ID: 0003_substation_registry
Revises: 0002_iam_and_core_reference_data
Create Date: 2026-07-02
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_substation_registry"
down_revision: Union[str, None] = "0002_iam_and_core_reference_data"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "substation",
        sa.Column("substation_id", sa.Uuid(), nullable=False),
        sa.Column("mnemonic", sa.String(length=10), nullable=False),
        sa.Column("official_name", sa.String(length=150), nullable=False),
        sa.Column("voltage_level_id", sa.SmallInteger(), nullable=False),
        sa.Column("region_id", sa.SmallInteger(), nullable=False),
        sa.Column("state_id", sa.SmallInteger(), nullable=False),
        sa.Column("grid_owner_id", sa.SmallInteger(), nullable=False),
        sa.Column("operational_status_id", sa.SmallInteger(), nullable=False),
        sa.Column("psse_bus_number", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Numeric(9, 6), nullable=True),
        sa.Column("longitude", sa.Numeric(9, 6), nullable=True),
        sa.Column("commissioned_date", sa.Date(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("substation_id"),
        sa.UniqueConstraint("mnemonic"),
        sa.UniqueConstraint("official_name"),
        sa.UniqueConstraint("psse_bus_number"),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude BETWEEN -90 AND 90)", name="ck_substation_lat_range"
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude BETWEEN -180 AND 180)",
            name="ck_substation_lon_range",
        ),
        sa.CheckConstraint(
            "(latitude IS NULL AND longitude IS NULL) OR "
            "(latitude IS NOT NULL AND longitude IS NOT NULL)",
            name="ck_substation_geo_pair",
        ),
        sa.ForeignKeyConstraint(
            ["voltage_level_id"], ["voltage_level.voltage_level_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["region_id"], ["region.region_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["state_id"], ["state.state_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["grid_owner_id"], ["grid_owner.grid_owner_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["operational_status_id"],
            ["operational_status.operational_status_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "uq_substation_mnemonic_ci", "substation", [sa.text("lower(mnemonic)")], unique=True
    )
    op.create_index(
        "uq_substation_name_ci", "substation", [sa.text("lower(official_name)")], unique=True
    )
    op.create_index("ix_substation_region", "substation", ["region_id"])
    op.create_index("ix_substation_state", "substation", ["state_id"])
    op.create_index("ix_substation_voltage", "substation", ["voltage_level_id"])
    op.create_index("ix_substation_owner", "substation", ["grid_owner_id"])
    op.create_index("ix_substation_status", "substation", ["operational_status_id"])

    op.create_table(
        "substation_alias",
        sa.Column("alias_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("substation_id", sa.Uuid(), nullable=False),
        sa.Column("alias_mnemonic", sa.String(length=10), nullable=True),
        sa.Column("alias_name", sa.String(length=150), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.CheckConstraint(
            "alias_mnemonic IS NOT NULL OR alias_name IS NOT NULL", name="ck_alias_has_value"
        ),
        # ON DELETE RESTRICT, not substation-registry.md §6's literal CASCADE
        # — see this file's module docstring and app/modules/
        # substation_registry/models.py's docstring for the CLAUDE.md F1
        # precedence reasoning.
        sa.ForeignKeyConstraint(
            ["substation_id"], ["substation.substation_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_substation_alias_lookup", "substation_alias", ["alias_mnemonic"])

    op.create_table(
        "substation_audit_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("substation_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(
            ["substation_id"], ["substation.substation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_audit_substation_time",
        "substation_audit_log",
        ["substation_id", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index("ix_audit_substation_time", table_name="substation_audit_log")
    op.drop_table("substation_audit_log")
    op.drop_index("ix_substation_alias_lookup", table_name="substation_alias")
    op.drop_table("substation_alias")
    op.drop_index("ix_substation_status", table_name="substation")
    op.drop_index("ix_substation_owner", table_name="substation")
    op.drop_index("ix_substation_voltage", table_name="substation")
    op.drop_index("ix_substation_state", table_name="substation")
    op.drop_index("ix_substation_region", table_name="substation")
    op.drop_index("uq_substation_name_ci", table_name="substation")
    op.drop_index("uq_substation_mnemonic_ci", table_name="substation")
    op.drop_table("substation")
