"""Equipment Registry: line_type (reference data), circuit, circuit_terminal,
equipment_registry_audit_log.

Per docs/architecture/equipment-registry-module.md §7.4-§7.6, §11 (ADR-006,
ADR-007) and docs/architecture/implementation-plan.md Phase 3.

Hand-written and manually reviewed against a real, locally reachable
PostgreSQL instance (`alembic upgrade head` run directly — see this phase's
implementation report) rather than machine-autogenerated, following the
same review discipline as 0003_substation_registry.py.

`line_type` ships in this same migration rather than a separate one: it
exists solely to support `circuit.line_type_id` and is introduced in the
same phase/PR as its only consumer, mirroring how 0002 already bundled "IAM
and Core Reference Data" together as one logical schema change.

Revision ID: 0004_equipment_registry_circuits
Revises: 0003_substation_registry
Create Date: 2026-07-05
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004_equipment_registry_circuits"
down_revision: Union[str, None] = "0003_substation_registry"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "line_type",
        sa.Column("line_type_id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("line_type_id"),
        sa.UniqueConstraint("code"),
    )

    op.create_table(
        "circuit",
        sa.Column("circuit_id", sa.Uuid(), nullable=False),
        sa.Column("bay_number", sa.String(length=20), nullable=False),
        sa.Column("voltage_level_id", sa.SmallInteger(), nullable=False),
        sa.Column("line_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("operational_status_id", sa.SmallInteger(), nullable=False),
        sa.Column("is_interconnector", sa.Boolean(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("circuit_id"),
        sa.ForeignKeyConstraint(
            ["voltage_level_id"], ["voltage_level.voltage_level_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["line_type_id"], ["line_type.line_type_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["operational_status_id"],
            ["operational_status.operational_status_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_circuit_voltage_level", "circuit", ["voltage_level_id"])
    op.create_index("ix_circuit_line_type", "circuit", ["line_type_id"])
    op.create_index("ix_circuit_status", "circuit", ["operational_status_id"])
    op.create_index("ix_circuit_bay_number", "circuit", ["bay_number"])

    op.create_table(
        "circuit_terminal",
        sa.Column("circuit_terminal_id", sa.Uuid(), nullable=False),
        sa.Column("circuit_id", sa.Uuid(), nullable=False),
        sa.Column("substation_id", sa.Uuid(), nullable=False),
        sa.Column("breaker_number", sa.String(length=20), nullable=False),
        sa.Column("commissioning_date", sa.Date(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("circuit_terminal_id"),
        # Business rule 6 (equipment-registry-module.md §9): no substation
        # may hold more than one terminal of the same circuit.
        sa.UniqueConstraint("circuit_id", "substation_id", name="uq_circuit_terminal_substation"),
        sa.ForeignKeyConstraint(["circuit_id"], ["circuit.circuit_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["substation_id"], ["substation.substation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_circuit_terminal_circuit", "circuit_terminal", ["circuit_id"])
    op.create_index("ix_circuit_terminal_substation", "circuit_terminal", ["substation_id"])

    op.create_table(
        "equipment_registry_audit_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("circuit_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(["circuit_id"], ["circuit.circuit_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_equipment_registry_audit_circuit_time",
        "equipment_registry_audit_log",
        ["circuit_id", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_equipment_registry_audit_circuit_time", table_name="equipment_registry_audit_log"
    )
    op.drop_table("equipment_registry_audit_log")
    op.drop_index("ix_circuit_terminal_substation", table_name="circuit_terminal")
    op.drop_index("ix_circuit_terminal_circuit", table_name="circuit_terminal")
    op.drop_table("circuit_terminal")
    op.drop_index("ix_circuit_bay_number", table_name="circuit")
    op.drop_index("ix_circuit_status", table_name="circuit")
    op.drop_index("ix_circuit_line_type", table_name="circuit")
    op.drop_index("ix_circuit_voltage_level", table_name="circuit")
    op.drop_table("circuit")
    op.drop_table("line_type")
