"""Transformer Registry (Phase 3.5): transformer, transformer_terminal,
transformer_audit_log.

Per the Phase 3.5 Transformer Registry spec and its Architecture Decision
Gate outcome (TransformerTerminal chosen over direct hv_/lv_ columns;
generated_short_name computed, not stored). See
docs/adr/ADR-008-substation-voltage-yard.md's Transformer Registry
addendum for the full architecture decision record.

**UAT correction (applied before this migration was ever committed/tagged
— edited in place per DEVELOPMENT.md §8's "never modify a committed
migration" rule, which does not apply here since this revision had not
yet been merged):** `transformer.substation_id` was added — a transformer
is substation-owned equipment in the Malaysian transmission/distribution
domain, never modeled as spanning two substations. Uniqueness moved from
a service-layer-only, cross-row check on
`(hv_switchyard_id, lv_switchyard_id, transformer_number)` to a real,
single-table database constraint,
`UNIQUE(substation_id, transformer_number)` — see the ADR-008 addendum's
UAT-correction entry.

Hand-written and manually reviewed against a real, locally reachable
PostgreSQL instance (`alembic upgrade head` run directly — see this
phase's implementation report), not machine-autogenerated, following the
same review discipline as every prior migration in this series.

No data backfill: these are new tables with no pre-existing rows.

Revision ID: 0008_transformer_registry
Revises: 0007_voltage_yard_metadata
Create Date: 2026-07-04
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008_transformer_registry"
down_revision: Union[str, None] = "0007_voltage_yard_metadata"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "transformer",
        sa.Column("transformer_id", sa.Uuid(), nullable=False),
        # UAT correction: transformers are substation-owned equipment, never
        # modeled as spanning two substations (Malaysian grid domain rule).
        sa.Column("substation_id", sa.Uuid(), nullable=False),
        sa.Column("transformer_number", sa.String(length=20), nullable=False),
        sa.Column("capacity_mva", sa.Numeric(8, 2), nullable=True),
        sa.Column("commissioning_date", sa.Date(), nullable=True),
        sa.Column("operational_status_id", sa.SmallInteger(), nullable=False),
        sa.Column("transformer_type", sa.String(length=50), nullable=True),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("transformer_id"),
        sa.CheckConstraint(
            "capacity_mva IS NULL OR capacity_mva > 0", name="ck_transformer_capacity_positive"
        ),
        # Real, single-table DB constraint (UAT correction) — a transformer
        # number is locally meaningful within one substation only.
        sa.UniqueConstraint(
            "substation_id", "transformer_number", name="uq_transformer_substation_number"
        ),
        sa.ForeignKeyConstraint(
            ["substation_id"], ["substation.substation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["operational_status_id"],
            ["operational_status.operational_status_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_transformer_substation", "transformer", ["substation_id"])
    op.create_index("ix_transformer_status", "transformer", ["operational_status_id"])
    op.create_index("ix_transformer_number", "transformer", ["transformer_number"])

    op.create_table(
        "transformer_terminal",
        sa.Column("transformer_terminal_id", sa.Uuid(), nullable=False),
        sa.Column("transformer_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("voltage_yard_id", sa.Uuid(), nullable=False),
        sa.Column("breaker_number", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("transformer_terminal_id"),
        # At most one HV and one LV terminal per transformer — the full
        # "exactly one of each, exactly two total" rule is enforced at the
        # service layer on creation (see transformer_terminal's own model
        # docstring).
        sa.UniqueConstraint("transformer_id", "side", name="uq_transformer_terminal_side"),
        sa.CheckConstraint("side IN ('HV', 'LV')", name="ck_transformer_terminal_side"),
        sa.ForeignKeyConstraint(
            ["transformer_id"], ["transformer.transformer_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["voltage_yard_id"],
            ["substation_voltage_yard.voltage_yard_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_transformer_terminal_transformer", "transformer_terminal", ["transformer_id"]
    )
    op.create_index(
        "ix_transformer_terminal_voltage_yard", "transformer_terminal", ["voltage_yard_id"]
    )

    op.create_table(
        "transformer_audit_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("transformer_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(
            ["transformer_id"], ["transformer.transformer_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_transformer_audit_transformer_time",
        "transformer_audit_log",
        ["transformer_id", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index("ix_transformer_audit_transformer_time", table_name="transformer_audit_log")
    op.drop_table("transformer_audit_log")
    op.drop_index("ix_transformer_terminal_voltage_yard", table_name="transformer_terminal")
    op.drop_index("ix_transformer_terminal_transformer", table_name="transformer_terminal")
    op.drop_table("transformer_terminal")
    op.drop_index("ix_transformer_number", table_name="transformer")
    op.drop_index("ix_transformer_status", table_name="transformer")
    op.drop_index("ix_transformer_substation", table_name="transformer")
    op.drop_table("transformer")
