"""Equipment Registry deletion/correction policy (Phase 3 follow-up):
adds `operational_status_id` to `substation_voltage_yard` and
`circuit_terminal`, enabling a mistakenly-created switchyard or circuit
terminal to be corrected via a new `ENTERED_IN_ERROR` reference-data status
(seeded separately by `app/reference_data/seed.py`, not this migration —
migrations create schema, seeding is a separate manual step, per this
project's established convention) instead of a hard delete.

`Transformer`/`Circuit` already carry `operational_status_id` (added in
earlier migrations) and gain no schema change here — only a new legal value
flows through their existing column once the reference row is seeded.
`TransformerTerminal` deliberately gains no status column: per the
Architecture Decision Gate for this policy, a mistaken transformer is
corrected at the whole-`Transformer` level (its HV/LV pair is intrinsic to
what it is), never at the level of one of its two terminals.

Data backfill: every existing `substation_voltage_yard`/`circuit_terminal`
row is backfilled to `ACTIVE`'s `operational_status_id`, looked up by code
rather than hardcoded, mirroring 0005_substation_voltage_yard.py's own
backfill style (nullable column -> `UPDATE` -> `NOT NULL`).

Also creates `substation_voltage_yard_audit_log` — deletion/correction
policy point 4 (correction actions must be audit logged) requires a
switchyard's status correction to be auditable, and no audit table
previously existed for this entity (a documented, pre-existing known
limitation this migration closes for the one field that now needs it).

Hand-written and manually reviewed against a real, locally reachable
PostgreSQL instance (`alembic upgrade head` run directly), not
machine-autogenerated, following the same review discipline as every prior
migration in this series.

Revision ID: 0009_correction_status
Revises: 0008_transformer_registry
Create Date: 2026-07-04

Note: named "0009_correction_status," not the fuller
"0009_engineering_correction_status," because `alembic_version.version_num`
is `VARCHAR(32)` (established earlier in this series) and the fuller name
exceeds that limit.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009_correction_status"
down_revision: Union[str, None] = "0008_transformer_registry"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- substation_voltage_yard ---------------------------------------------------
    op.add_column(
        "substation_voltage_yard",
        sa.Column("operational_status_id", sa.SmallInteger(), nullable=True),
    )
    op.execute(
        """
        UPDATE substation_voltage_yard
        SET operational_status_id = (
            SELECT operational_status_id FROM operational_status WHERE code = 'ACTIVE'
        )
        """
    )
    op.alter_column("substation_voltage_yard", "operational_status_id", nullable=False)
    op.create_foreign_key(
        "substation_voltage_yard_operational_status_id_fkey",
        "substation_voltage_yard",
        "operational_status",
        ["operational_status_id"],
        ["operational_status_id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        "ix_substation_voltage_yard_status", "substation_voltage_yard", ["operational_status_id"]
    )

    # --- circuit_terminal -----------------------------------------------------------
    op.add_column(
        "circuit_terminal",
        sa.Column("operational_status_id", sa.SmallInteger(), nullable=True),
    )
    op.execute(
        """
        UPDATE circuit_terminal
        SET operational_status_id = (
            SELECT operational_status_id FROM operational_status WHERE code = 'ACTIVE'
        )
        """
    )
    op.alter_column("circuit_terminal", "operational_status_id", nullable=False)
    op.create_foreign_key(
        "circuit_terminal_operational_status_id_fkey",
        "circuit_terminal",
        "operational_status",
        ["operational_status_id"],
        ["operational_status_id"],
        ondelete="RESTRICT",
    )
    op.create_index("ix_circuit_terminal_status", "circuit_terminal", ["operational_status_id"])

    # --- substation_voltage_yard_audit_log -------------------------------------------
    op.create_table(
        "substation_voltage_yard_audit_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("voltage_yard_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(
            ["voltage_yard_id"],
            ["substation_voltage_yard.voltage_yard_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_substation_voltage_yard_audit_yard_time",
        "substation_voltage_yard_audit_log",
        ["voltage_yard_id", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_substation_voltage_yard_audit_yard_time",
        table_name="substation_voltage_yard_audit_log",
    )
    op.drop_table("substation_voltage_yard_audit_log")

    op.drop_index("ix_circuit_terminal_status", table_name="circuit_terminal")
    op.drop_constraint(
        "circuit_terminal_operational_status_id_fkey", "circuit_terminal", type_="foreignkey"
    )
    op.drop_column("circuit_terminal", "operational_status_id")

    op.drop_index("ix_substation_voltage_yard_status", table_name="substation_voltage_yard")
    op.drop_constraint(
        "substation_voltage_yard_operational_status_id_fkey",
        "substation_voltage_yard",
        type_="foreignkey",
    )
    op.drop_column("substation_voltage_yard", "operational_status_id")
