"""PSS/E Integration: raw_file_import_batch, topology_version, topology_bus,
topology_branch, topology_transformer, load_snapshot, load_snapshot_bus_state,
load_snapshot_element_state, network_load, network_generator,
equipment_topology_map, psse_import_audit_log.

Per docs/architecture/psse-integration-module.md §5/§8a/§11, ADR-003
(topology/load separation), ADR-006 (Connectivity Registry vs. PSS/E
topology), ADR-007 (EquipmentTopologyMap) and docs/architecture/
implementation-plan.md Phase 4.

Hand-written and manually reviewed, mirroring 0004_equipment_registry_
circuits.py's own review discipline rather than machine-autogenerated.

`raw_file_import_batch` <-> `topology_version` <-> `load_snapshot` is a
genuine 3-table FK cycle: a TopologyVersion/LoadSnapshot points back at the
batch it was created from (required), and a batch points forward at the
TopologyVersion/LoadSnapshot it produced (nullable, set only after those
rows exist). `raw_file_import_batch` is therefore created first without
its `topology_version_id`/`load_snapshot_id` foreign keys; those two are
added via `op.create_foreign_key` once all three tables exist, matching
`models.py`'s own `use_alter=True` markers on those columns.

Revision ID: 0012_psse_integration
Revises: 0011_breaker_convention
Create Date: 2026-07-05
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012_psse_integration"
down_revision: Union[str, None] = "0011_breaker_convention"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# JSONB on PostgreSQL, plain JSON elsewhere — mirrors `models.py`'s own
# `_JsonVariant` and 0002's `_ReferenceKey` dialect-variant precedent.
_JsonVariant = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    # --- raw_file_import_batch (topology_version_id/load_snapshot_id FKs added below) ---
    op.create_table(
        "raw_file_import_batch",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_reference", sa.String(length=255), nullable=False),
        sa.Column("imported_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("import_type", sa.String(length=30), nullable=False),
        sa.Column("computed_signature", sa.String(length=64), nullable=True),
        sa.Column("topology_version_id", sa.Uuid(), nullable=True),
        sa.Column("load_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("warnings", _JsonVariant, nullable=False),
        sa.Column("fatal_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("batch_id"),
        sa.CheckConstraint(
            "import_type IN ('FULL_TOPOLOGY_WITH_LOAD', 'LOAD_ONLY')",
            name="ck_raw_file_import_batch_type",
        ),
        sa.CheckConstraint(
            "status IN ('Parsing', 'Completed', 'CompletedWithWarnings', 'Failed')",
            name="ck_raw_file_import_batch_status",
        ),
        sa.ForeignKeyConstraint(["imported_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_raw_file_import_batch_status", "raw_file_import_batch", ["status"])
    op.create_index(
        "ix_raw_file_import_batch_topology_version",
        "raw_file_import_batch",
        ["topology_version_id"],
    )

    # --- topology_version --------------------------------------------------------------
    op.create_table(
        "topology_version",
        sa.Column("topology_version_id", sa.Uuid(), nullable=False),
        sa.Column("signature", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_from_batch_id", sa.Uuid(), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("topology_version_id"),
        sa.UniqueConstraint("signature"),
        sa.CheckConstraint(
            "status IN ('Imported', 'Current', 'Superseded')",
            name="ck_topology_version_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_from_batch_id"], ["raw_file_import_batch.batch_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_topology_version_status", "topology_version", ["status"])

    # --- load_snapshot -------------------------------------------------------------------
    op.create_table(
        "load_snapshot",
        sa.Column("load_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("topology_version_id", sa.Uuid(), nullable=False),
        sa.Column("created_from_batch_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("load_snapshot_id"),
        sa.CheckConstraint(
            "status IN ('Imported', 'Current', 'Superseded')", name="ck_load_snapshot_status"
        ),
        sa.ForeignKeyConstraint(
            ["topology_version_id"],
            ["topology_version.topology_version_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_from_batch_id"], ["raw_file_import_batch.batch_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_load_snapshot_topology_version", "load_snapshot", ["topology_version_id"])
    op.create_index("ix_load_snapshot_status", "load_snapshot", ["status"])

    # --- close the batch <-> topology_version/load_snapshot cycle ------------------------
    op.create_foreign_key(
        "fk_raw_file_import_batch_topology_version",
        "raw_file_import_batch",
        "topology_version",
        ["topology_version_id"],
        ["topology_version_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_raw_file_import_batch_load_snapshot",
        "raw_file_import_batch",
        "load_snapshot",
        ["load_snapshot_id"],
        ["load_snapshot_id"],
        ondelete="RESTRICT",
    )

    # --- topology_bus --------------------------------------------------------------------
    op.create_table(
        "topology_bus",
        sa.Column("topology_bus_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topology_version_id", sa.Uuid(), nullable=False),
        sa.Column("bus_number", sa.Integer(), nullable=False),
        sa.Column("bus_name", sa.String(length=40), nullable=True),
        sa.Column("base_kv", sa.Numeric(8, 3), nullable=False),
        sa.Column("substation_id", sa.Uuid(), nullable=True),
        sa.Column("psse_area", sa.Integer(), nullable=True),
        sa.Column("psse_zone", sa.Integer(), nullable=True),
        sa.Column("psse_owner", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("topology_bus_id"),
        sa.UniqueConstraint("topology_version_id", "bus_number", name="uq_topology_bus_number"),
        sa.ForeignKeyConstraint(
            ["topology_version_id"],
            ["topology_version.topology_version_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["substation_id"], ["substation.substation_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_topology_bus_version", "topology_bus", ["topology_version_id"])
    op.create_index("ix_topology_bus_substation", "topology_bus", ["substation_id"])

    # --- topology_branch -------------------------------------------------------------------
    op.create_table(
        "topology_branch",
        sa.Column("topology_branch_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topology_version_id", sa.Uuid(), nullable=False),
        sa.Column("from_bus_id", sa.Integer(), nullable=False),
        sa.Column("to_bus_id", sa.Integer(), nullable=False),
        sa.Column("ckt_id", sa.String(length=2), nullable=False),
        sa.Column("r", sa.Numeric(12, 6), nullable=False),
        sa.Column("x", sa.Numeric(12, 6), nullable=False),
        sa.Column("b", sa.Numeric(12, 6), nullable=False),
        sa.Column("rate_a", sa.Numeric(10, 2), nullable=True),
        sa.Column("rate_b", sa.Numeric(10, 2), nullable=True),
        sa.Column("rate_c", sa.Numeric(10, 2), nullable=True),
        sa.PrimaryKeyConstraint("topology_branch_id"),
        sa.ForeignKeyConstraint(
            ["topology_version_id"],
            ["topology_version.topology_version_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_bus_id"], ["topology_bus.topology_bus_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["to_bus_id"], ["topology_bus.topology_bus_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_topology_branch_version", "topology_branch", ["topology_version_id"])
    op.create_index("ix_topology_branch_from_bus", "topology_branch", ["from_bus_id"])
    op.create_index("ix_topology_branch_to_bus", "topology_branch", ["to_bus_id"])

    # --- topology_transformer ----------------------------------------------------------
    op.create_table(
        "topology_transformer",
        sa.Column("topology_transformer_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topology_version_id", sa.Uuid(), nullable=False),
        sa.Column("from_bus_id", sa.Integer(), nullable=False),
        sa.Column("to_bus_id", sa.Integer(), nullable=False),
        sa.Column("tertiary_bus_id", sa.Integer(), nullable=True),
        sa.Column("ckt_id", sa.String(length=2), nullable=False),
        sa.Column("r", sa.Numeric(12, 6), nullable=False),
        sa.Column("x", sa.Numeric(12, 6), nullable=False),
        sa.Column("rate_a", sa.Numeric(10, 2), nullable=True),
        sa.PrimaryKeyConstraint("topology_transformer_id"),
        sa.ForeignKeyConstraint(
            ["topology_version_id"],
            ["topology_version.topology_version_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_bus_id"], ["topology_bus.topology_bus_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["to_bus_id"], ["topology_bus.topology_bus_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tertiary_bus_id"], ["topology_bus.topology_bus_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index(
        "ix_topology_transformer_version", "topology_transformer", ["topology_version_id"]
    )
    op.create_index("ix_topology_transformer_from_bus", "topology_transformer", ["from_bus_id"])
    op.create_index("ix_topology_transformer_to_bus", "topology_transformer", ["to_bus_id"])

    # --- load_snapshot_bus_state ---------------------------------------------------------
    op.create_table(
        "load_snapshot_bus_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("load_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("topology_bus_id", sa.Integer(), nullable=False),
        sa.Column("bus_type", sa.SmallInteger(), nullable=False),
        sa.Column("voltage_mag", sa.Numeric(8, 5), nullable=True),
        sa.Column("voltage_angle", sa.Numeric(8, 4), nullable=True),
        sa.Column("in_service", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "load_snapshot_id", "topology_bus_id", name="uq_load_snapshot_bus_state"
        ),
        sa.ForeignKeyConstraint(
            ["load_snapshot_id"], ["load_snapshot.load_snapshot_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["topology_bus_id"], ["topology_bus.topology_bus_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index(
        "ix_load_snapshot_bus_state_snapshot", "load_snapshot_bus_state", ["load_snapshot_id"]
    )

    # --- load_snapshot_element_state -----------------------------------------------------
    op.create_table(
        "load_snapshot_element_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("load_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("topology_branch_id", sa.Integer(), nullable=True),
        sa.Column("topology_transformer_id", sa.Integer(), nullable=True),
        sa.Column("in_service", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "(topology_branch_id IS NOT NULL) != (topology_transformer_id IS NOT NULL)",
            name="ck_load_snapshot_element_state_xor",
        ),
        sa.ForeignKeyConstraint(
            ["load_snapshot_id"], ["load_snapshot.load_snapshot_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["topology_branch_id"],
            ["topology_branch.topology_branch_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topology_transformer_id"],
            ["topology_transformer.topology_transformer_id"],
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "ix_load_snapshot_element_state_snapshot",
        "load_snapshot_element_state",
        ["load_snapshot_id"],
    )

    # --- network_load --------------------------------------------------------------------
    op.create_table(
        "network_load",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("load_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("topology_bus_id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.String(length=2), nullable=False),
        sa.Column("p_mw", sa.Numeric(10, 3), nullable=False),
        sa.Column("q_mvar", sa.Numeric(10, 3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "load_snapshot_id", "topology_bus_id", "load_id", name="uq_network_load"
        ),
        sa.ForeignKeyConstraint(
            ["load_snapshot_id"], ["load_snapshot.load_snapshot_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["topology_bus_id"], ["topology_bus.topology_bus_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_network_load_snapshot", "network_load", ["load_snapshot_id"])

    # --- network_generator -----------------------------------------------------------------
    op.create_table(
        "network_generator",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("load_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("topology_bus_id", sa.Integer(), nullable=False),
        sa.Column("gen_id", sa.String(length=2), nullable=False),
        sa.Column("p_gen", sa.Numeric(10, 3), nullable=True),
        sa.Column("q_gen", sa.Numeric(10, 3), nullable=True),
        sa.Column("p_max", sa.Numeric(10, 3), nullable=True),
        sa.Column("p_min", sa.Numeric(10, 3), nullable=True),
        sa.Column("q_max", sa.Numeric(10, 3), nullable=True),
        sa.Column("q_min", sa.Numeric(10, 3), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "load_snapshot_id", "topology_bus_id", "gen_id", name="uq_network_generator"
        ),
        sa.ForeignKeyConstraint(
            ["load_snapshot_id"], ["load_snapshot.load_snapshot_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["topology_bus_id"], ["topology_bus.topology_bus_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_network_generator_snapshot", "network_generator", ["load_snapshot_id"])

    # --- equipment_topology_map -----------------------------------------------------------
    op.create_table(
        "equipment_topology_map",
        sa.Column("map_id", sa.Uuid(), nullable=False),
        sa.Column("topology_version_id", sa.Uuid(), nullable=False),
        sa.Column("circuit_terminal_id", sa.Uuid(), nullable=False),
        sa.Column("topology_branch_id", sa.Integer(), nullable=True),
        sa.Column("topology_transformer_id", sa.Integer(), nullable=True),
        sa.Column("match_outcome", sa.String(length=20), nullable=False),
        sa.Column("discrepancy_resolution", sa.String(length=20), nullable=True),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("map_id"),
        sa.CheckConstraint(
            "match_outcome IN ('clean_match', 'unmatched', 'discrepancy')",
            name="ck_equipment_topology_map_outcome",
        ),
        sa.CheckConstraint(
            "discrepancy_resolution IS NULL OR discrepancy_resolution IN ('accepted', 'rejected')",
            name="ck_equipment_topology_map_resolution",
        ),
        sa.CheckConstraint(
            "NOT (topology_branch_id IS NOT NULL AND topology_transformer_id IS NOT NULL)",
            name="ck_equipment_topology_map_target_xor",
        ),
        sa.UniqueConstraint(
            "topology_version_id",
            "circuit_terminal_id",
            name="uq_equipment_topology_map_terminal",
        ),
        sa.ForeignKeyConstraint(
            ["topology_version_id"],
            ["topology_version.topology_version_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["circuit_terminal_id"],
            ["circuit_terminal.circuit_terminal_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topology_branch_id"],
            ["topology_branch.topology_branch_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topology_transformer_id"],
            ["topology_transformer.topology_transformer_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["resolved_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_equipment_topology_map_version", "equipment_topology_map", ["topology_version_id"]
    )
    op.create_index(
        "ix_equipment_topology_map_outcome", "equipment_topology_map", ["match_outcome"]
    )

    # --- psse_import_audit_log ------------------------------------------------------------
    op.create_table(
        "psse_import_audit_log",
        sa.Column("log_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        # 80, not 64: EquipmentTopologyMap's own audit entries key on a
        # composite "{topology_version_id}:{circuit_terminal_id}" (2 UUIDs +
        # separator = 73 chars).
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_psse_import_audit_entity",
        "psse_import_audit_log",
        ["entity_type", "entity_id", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index("ix_psse_import_audit_entity", table_name="psse_import_audit_log")
    op.drop_table("psse_import_audit_log")

    op.drop_index("ix_equipment_topology_map_outcome", table_name="equipment_topology_map")
    op.drop_index("ix_equipment_topology_map_version", table_name="equipment_topology_map")
    op.drop_table("equipment_topology_map")

    op.drop_index("ix_network_generator_snapshot", table_name="network_generator")
    op.drop_table("network_generator")

    op.drop_index("ix_network_load_snapshot", table_name="network_load")
    op.drop_table("network_load")

    op.drop_index(
        "ix_load_snapshot_element_state_snapshot", table_name="load_snapshot_element_state"
    )
    op.drop_table("load_snapshot_element_state")

    op.drop_index("ix_load_snapshot_bus_state_snapshot", table_name="load_snapshot_bus_state")
    op.drop_table("load_snapshot_bus_state")

    op.drop_index("ix_topology_transformer_to_bus", table_name="topology_transformer")
    op.drop_index("ix_topology_transformer_from_bus", table_name="topology_transformer")
    op.drop_index("ix_topology_transformer_version", table_name="topology_transformer")
    op.drop_table("topology_transformer")

    op.drop_index("ix_topology_branch_to_bus", table_name="topology_branch")
    op.drop_index("ix_topology_branch_from_bus", table_name="topology_branch")
    op.drop_index("ix_topology_branch_version", table_name="topology_branch")
    op.drop_table("topology_branch")

    op.drop_index("ix_topology_bus_substation", table_name="topology_bus")
    op.drop_index("ix_topology_bus_version", table_name="topology_bus")
    op.drop_table("topology_bus")

    op.drop_constraint(
        "fk_raw_file_import_batch_load_snapshot", "raw_file_import_batch", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_raw_file_import_batch_topology_version", "raw_file_import_batch", type_="foreignkey"
    )

    op.drop_index("ix_load_snapshot_status", table_name="load_snapshot")
    op.drop_index("ix_load_snapshot_topology_version", table_name="load_snapshot")
    op.drop_table("load_snapshot")

    op.drop_index("ix_topology_version_status", table_name="topology_version")
    op.drop_table("topology_version")

    op.drop_index("ix_raw_file_import_batch_topology_version", table_name="raw_file_import_batch")
    op.drop_index("ix_raw_file_import_batch_status", table_name="raw_file_import_batch")
    op.drop_table("raw_file_import_batch")
