"""Automatic Load Shedding Functionality Registry (ADR-011).

Creates `automatic_load_shedding_functionality` and its audit log
(`automatic_load_shedding_functionality_audit_log`) — the new, dedicated
Engineering Registry module retiring the earlier "Relay Registry"
direction sketched (never built) in equipment-registry-module.md §7.8. See
docs/adr/ADR-011-automatic-load-shedding-functionality-registry.md and
docs/architecture/automatic-load-shedding-functionality-registry-module.md
for the full architecture.

References `circuit_terminal.circuit_terminal_id`/
`transformer_terminal.transformer_terminal_id` (Equipment Registry, already
exists) and `user.user_id` (IAM, already exists) — no cross-module table is
altered.

Hand-written and manually reviewed, following the same review discipline as
every prior migration in this series — not machine-autogenerated.

Engineering refinement (edited in place — this migration was never merged,
so per this project's own migration discipline, correcting it directly is
the pre-acceptance iteration path, not a "correction to committed history"
CLAUDE.md §5.2 would otherwise require a new migration for):

1. The lifecycle was first simplified from four states
   (Added/Active/Inactive/Decommissioned) to three
   (Active/Inactive/Decommissioned).
2. Status Model Refinement (this edit): the *persisted* lifecycle column
   is renamed from `status` to `lifecycle_status` and narrowed to two
   values (`ACTIVE`/`DECOMMISSIONED`) — `INACTIVE` is removed entirely.
   The three-value status an engineer actually sees (Available / Assigned
   / Decommissioned) is now computed at read time by the service layer
   (Assigned iff a future UFLS/UVLS module reports the terminal as
   currently assigned) and is never itself a stored column — see
   service.py's own module docstring. No other schema shape changed.

Revision ID: 0014_alsf_registry
Revises: 0013_network_load_owner
Create Date: 2026-07-09
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0014_alsf_registry"
down_revision: Union[str, None] = "0013_network_load_owner"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "automatic_load_shedding_functionality",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("circuit_terminal_id", sa.Uuid(), nullable=True),
        sa.Column("transformer_terminal_id", sa.Uuid(), nullable=True),
        sa.Column("ufls_function", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("uvls_function", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "lifecycle_status", sa.String(length=20), nullable=False, server_default="ACTIVE"
        ),
        sa.Column("relay_make", sa.String(length=100), nullable=True),
        sa.Column("relay_model", sa.String(length=100), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["circuit_terminal_id"],
            ["circuit_terminal.circuit_terminal_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transformer_terminal_id"],
            ["transformer_terminal.transformer_terminal_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            "target_type IN ('CIRCUIT_TERMINAL','TRANSFORMER_TERMINAL')",
            name="ck_alsf_target_type",
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('ACTIVE','DECOMMISSIONED')",
            name="ck_alsf_lifecycle_status",
        ),
        sa.CheckConstraint(
            "(target_type = 'CIRCUIT_TERMINAL' AND circuit_terminal_id IS NOT NULL "
            "AND transformer_terminal_id IS NULL) "
            "OR "
            "(target_type = 'TRANSFORMER_TERMINAL' AND transformer_terminal_id IS NOT NULL "
            "AND circuit_terminal_id IS NULL)",
            name="ck_alsf_target_xor",
        ),
        sa.CheckConstraint(
            "ufls_function IS TRUE OR uvls_function IS TRUE",
            name="ck_alsf_function_flags",
        ),
    )
    op.create_index(
        "uq_alsf_circuit_terminal_active",
        "automatic_load_shedding_functionality",
        ["circuit_terminal_id"],
        unique=True,
        postgresql_where=sa.text(
            "lifecycle_status != 'DECOMMISSIONED' AND circuit_terminal_id IS NOT NULL"
        ),
        sqlite_where=sa.text(
            "lifecycle_status != 'DECOMMISSIONED' AND circuit_terminal_id IS NOT NULL"
        ),
    )
    op.create_index(
        "uq_alsf_transformer_terminal_active",
        "automatic_load_shedding_functionality",
        ["transformer_terminal_id"],
        unique=True,
        postgresql_where=sa.text(
            "lifecycle_status != 'DECOMMISSIONED' AND transformer_terminal_id IS NOT NULL"
        ),
        sqlite_where=sa.text(
            "lifecycle_status != 'DECOMMISSIONED' AND transformer_terminal_id IS NOT NULL"
        ),
    )
    op.create_index(
        "ix_alsf_circuit_terminal",
        "automatic_load_shedding_functionality",
        ["circuit_terminal_id"],
    )
    op.create_index(
        "ix_alsf_transformer_terminal",
        "automatic_load_shedding_functionality",
        ["transformer_terminal_id"],
    )
    op.create_index(
        "ix_alsf_lifecycle_status", "automatic_load_shedding_functionality", ["lifecycle_status"]
    )
    op.create_index(
        "ix_alsf_ufls_function", "automatic_load_shedding_functionality", ["ufls_function"]
    )
    op.create_index(
        "ix_alsf_uvls_function", "automatic_load_shedding_functionality", ["uvls_function"]
    )

    op.create_table(
        "automatic_load_shedding_functionality_audit_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("functionality_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(
            ["functionality_id"],
            ["automatic_load_shedding_functionality.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_alsf_audit_functionality_time",
        "automatic_load_shedding_functionality_audit_log",
        ["functionality_id", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_alsf_audit_functionality_time",
        table_name="automatic_load_shedding_functionality_audit_log",
    )
    op.drop_table("automatic_load_shedding_functionality_audit_log")

    op.drop_index("ix_alsf_uvls_function", table_name="automatic_load_shedding_functionality")
    op.drop_index("ix_alsf_ufls_function", table_name="automatic_load_shedding_functionality")
    op.drop_index("ix_alsf_lifecycle_status", table_name="automatic_load_shedding_functionality")
    op.drop_index(
        "ix_alsf_transformer_terminal", table_name="automatic_load_shedding_functionality"
    )
    op.drop_index("ix_alsf_circuit_terminal", table_name="automatic_load_shedding_functionality")
    op.drop_index(
        "uq_alsf_transformer_terminal_active",
        table_name="automatic_load_shedding_functionality",
    )
    op.drop_index(
        "uq_alsf_circuit_terminal_active", table_name="automatic_load_shedding_functionality"
    )
    op.drop_table("automatic_load_shedding_functionality")
