"""Sensitive Customer Registry (ADR-012, amended by ADR-013).

Creates `facility_sector`, `sensitivity_classification` (module-owned
reference data), `sensitive_facility`,
`sensitive_facility_transformer_terminal` (the many-to-many supply-point
association, ADR-013), and their shared audit log
(`sensitive_customer_registry_audit_log`). See
docs/adr/ADR-012-sensitive-customer-registry-architecture.md,
docs/adr/ADR-013-sensitive-facility-multiple-transformer-terminals.md,
docs/architecture/sensitive-customer-registry-module.md, and
docs/architecture/sensitive-customer-registry-implementation-spec.md for
the full architecture.

References `transformer_terminal.transformer_terminal_id` (Equipment
Registry, already exists) and `user.user_id` (IAM, already exists) — no
cross-module table is altered. Unlike ALSF, there is no Circuit Terminal
reference at all, and no per-terminal uniqueness constraint (many
facilities may share one terminal, the deliberate inverse of ALSF's own
rule — implementation spec §5.1). Since ADR-013, one facility may itself
be associated with many terminals — modelled as a genuine association
table, not a column on `sensitive_facility`.

Hand-written and manually reviewed, following the same review discipline
as every prior migration in this series — not machine-autogenerated. This
migration was never merged prior to ADR-013, so per this project's own
established convention for pre-merge migrations (`0014_alsf_registry`'s
own precedent), it is edited in place here rather than superseded by a
new migration.

Revision ID: 0015_sensitive_customer_registry
Revises: 0014_alsf_registry
Create Date: 2026-07-10
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0015_sensitive_customer_registry"
down_revision: Union[str, None] = "0014_alsf_registry"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- facility_sector (module-owned reference data) ---------------------
    op.create_table(
        "facility_sector",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_facility_sector_code"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )

    # --- sensitivity_classification (module-owned reference data) ----------
    op.create_table(
        "sensitivity_classification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_sensitivity_classification_code"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
    )

    # --- sensitive_facility --------------------------------------------------
    op.create_table(
        "sensitive_facility",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("facility_sector_id", sa.Integer(), nullable=False),
        sa.Column("sensitivity_classification_id", sa.Integer(), nullable=False),
        sa.Column(
            "lifecycle_status", sa.String(length=20), nullable=False, server_default="ACTIVE"
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["facility_sector_id"], ["facility_sector.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["sensitivity_classification_id"],
            ["sensitivity_classification.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            "lifecycle_status IN ('ACTIVE','ARCHIVED','ENTERED_IN_ERROR')",
            name="ck_scr_facility_lifecycle_status",
        ),
    )
    op.create_index("ix_scr_facility_sector", "sensitive_facility", ["facility_sector_id"])
    op.create_index(
        "ix_scr_facility_sensitivity_classification",
        "sensitive_facility",
        ["sensitivity_classification_id"],
    )
    op.create_index("ix_scr_facility_lifecycle_status", "sensitive_facility", ["lifecycle_status"])

    # --- sensitive_facility_transformer_terminal (supply-point association,
    # ADR-013 — many-to-many; current-state only, no validity window) -------
    op.create_table(
        "sensitive_facility_transformer_terminal",
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("transformer_terminal_id", sa.Uuid(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("facility_id", "transformer_terminal_id"),
        sa.ForeignKeyConstraint(["facility_id"], ["sensitive_facility.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["transformer_terminal_id"],
            ["transformer_terminal.transformer_terminal_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["added_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        # Deliberately NO additional uniqueness constraint beyond the
        # composite primary key — many facilities may share one terminal,
        # and (since ADR-013) one facility may have many terminals.
    )
    op.create_index(
        "ix_scr_facility_terminal_terminal",
        "sensitive_facility_transformer_terminal",
        ["transformer_terminal_id"],
    )

    # --- sensitive_customer_registry_audit_log (shared, polymorphic) -------
    op.create_table(
        "sensitive_customer_registry_audit_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subject_type", sa.String(length=30), nullable=False),
        sa.Column("sensitive_facility_id", sa.Uuid(), nullable=True),
        sa.Column("facility_sector_id", sa.Integer(), nullable=True),
        sa.Column("sensitivity_classification_id", sa.Integer(), nullable=True),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(
            ["sensitive_facility_id"], ["sensitive_facility.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["facility_sector_id"], ["facility_sector.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["sensitivity_classification_id"],
            ["sensitivity_classification.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            "subject_type IN ('SENSITIVE_FACILITY','FACILITY_SECTOR','SENSITIVITY_CLASSIFICATION')",
            name="ck_scr_audit_subject_type",
        ),
        sa.CheckConstraint(
            "(subject_type = 'SENSITIVE_FACILITY' AND sensitive_facility_id IS NOT NULL "
            "AND facility_sector_id IS NULL AND sensitivity_classification_id IS NULL) "
            "OR "
            "(subject_type = 'FACILITY_SECTOR' AND facility_sector_id IS NOT NULL "
            "AND sensitive_facility_id IS NULL AND sensitivity_classification_id IS NULL) "
            "OR "
            "(subject_type = 'SENSITIVITY_CLASSIFICATION' "
            "AND sensitivity_classification_id IS NOT NULL "
            "AND sensitive_facility_id IS NULL AND facility_sector_id IS NULL)",
            name="ck_scr_audit_subject_xor",
        ),
    )
    op.create_index(
        "ix_scr_audit_facility_time",
        "sensitive_customer_registry_audit_log",
        ["sensitive_facility_id", sa.text("changed_at DESC")],
    )
    op.create_index(
        "ix_scr_audit_sector_time",
        "sensitive_customer_registry_audit_log",
        ["facility_sector_id", sa.text("changed_at DESC")],
    )
    op.create_index(
        "ix_scr_audit_classification_time",
        "sensitive_customer_registry_audit_log",
        ["sensitivity_classification_id", sa.text("changed_at DESC")],
    )
    op.create_index(
        "ix_scr_audit_subject_type", "sensitive_customer_registry_audit_log", ["subject_type"]
    )


def downgrade() -> None:
    op.drop_index("ix_scr_audit_subject_type", table_name="sensitive_customer_registry_audit_log")
    op.drop_index(
        "ix_scr_audit_classification_time", table_name="sensitive_customer_registry_audit_log"
    )
    op.drop_index("ix_scr_audit_sector_time", table_name="sensitive_customer_registry_audit_log")
    op.drop_index("ix_scr_audit_facility_time", table_name="sensitive_customer_registry_audit_log")
    op.drop_table("sensitive_customer_registry_audit_log")

    op.drop_index(
        "ix_scr_facility_terminal_terminal", table_name="sensitive_facility_transformer_terminal"
    )
    op.drop_table("sensitive_facility_transformer_terminal")

    op.drop_index("ix_scr_facility_lifecycle_status", table_name="sensitive_facility")
    op.drop_index("ix_scr_facility_sensitivity_classification", table_name="sensitive_facility")
    op.drop_index("ix_scr_facility_sector", table_name="sensitive_facility")
    op.drop_table("sensitive_facility")

    op.drop_table("sensitivity_classification")
    op.drop_table("facility_sector")
