"""Substation Registry enhancement: GM Zone (Grid Maintenance Zone) metadata.

Project Owner-approved enhancement — adds `gm_zone` (a new Core Platform
reference/lookup table, mirroring `region`'s own shape and placement
exactly per docs/architecture/substation-registry.md's GM Zone status
update) and a `substation.gm_zone_id` FK column.

GM Zone identifies the organizational Grid Maintenance Zone responsible
for maintaining a substation — purely organizational, not electrical, and
independent of `region` (a grid-planning grouping). The two attributes are
deliberately uncoupled: no FK or constraint ties a `gm_zone` row to a
`region` row.

`gm_zone_id` is `NOT NULL`, exactly like `region_id`/`state_id`/
`grid_owner_id` — "Each Substation shall reference exactly one GM Zone" is
a universal invariant, not conditional on status. The column is still
added as nullable first and only then tightened to `NOT NULL` within this
same migration (rather than a single `NOT NULL` column add), because
`ALTER TABLE ... ADD COLUMN ... NOT NULL` has no default to backfill
existing `substation` rows with — this migration intentionally does not
invent one. The Project Owner assigned a valid GM Zone to every
pre-existing Substation in the development database directly (not via
this migration), and `upgrade()` relies on that already being true: the
final `SET NOT NULL` fails loudly, rather than silently inventing data,
if any row is still missing a value. (This migration has never been
merged — this is that same review-and-tighten pass, applied in place
rather than as a separate follow-up migration, per this project's
established convention for still-unmerged migrations.)

Hand-written and manually reviewed, following the same review discipline
as every prior migration in this series — not machine-autogenerated.

Revision ID: 0016_gm_zone
Revises: 0015_sensitive_customer_registry
Create Date: 2026-07-11
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0016_gm_zone"
down_revision: Union[str, None] = "0015_sensitive_customer_registry"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- gm_zone (Core Platform reference data, mirrors region) --------------
    op.create_table(
        "gm_zone",
        sa.Column("gm_zone_id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("gm_zone_id"),
        sa.UniqueConstraint("code", name="uq_gm_zone_code"),
    )

    # --- substation.gm_zone_id (NOT NULL — see module docstring) --------------
    # Added nullable first (no default exists to backfill with), then
    # tightened to NOT NULL — relies on every pre-existing row already
    # having a valid value (Project Owner data assignment); fails loudly,
    # not silently, if that is untrue.
    op.add_column("substation", sa.Column("gm_zone_id", sa.SmallInteger(), nullable=True))
    op.create_foreign_key(
        "substation_gm_zone_id_fkey",
        "substation",
        "gm_zone",
        ["gm_zone_id"],
        ["gm_zone_id"],
        ondelete="RESTRICT",
    )
    op.create_index("ix_substation_gm_zone", "substation", ["gm_zone_id"])
    op.alter_column("substation", "gm_zone_id", nullable=False)


def downgrade() -> None:
    op.drop_index("ix_substation_gm_zone", table_name="substation")
    op.drop_constraint("substation_gm_zone_id_fkey", "substation", type_="foreignkey")
    op.drop_column("substation", "gm_zone_id")

    op.drop_table("gm_zone")
