"""Engineering Parameter Configuration (ADR-021).

Creates `engineering_parameter` (current, audited value of every named
platform-wide engineering parameter — e.g. `mw_tolerance_percentage`) and
its own append-only `engineering_parameter_audit_log`. See
docs/adr/ADR-021-engineering-parameter-configuration-ownership.md and
docs/architecture/engineering-parameter-configuration-architecture.md for
the full architecture.

References `user.user_id` (IAM, already exists) only — no cross-module
table is altered. `updated_by_user_id`/`changed_by_user_id` are nullable
to accommodate this module's own bootstrap-seed exception (the one
architecture-approved initial parameter, `mw_tolerance_percentage`, is
seeded with `actor_user_id=None`, mirroring IAMAuditLog's own documented
"nullable only for the bootstrap exception").

Hand-written and manually reviewed, following the same review discipline
as every prior migration in this series — not machine-autogenerated.

Revision ID: 0017_engineering_parameters
Revises: 0016_gm_zone
Create Date: 2026-07-15

Note: the revision id is `0017_engineering_parameters`, not the fuller
`0017_engineering_parameter_configuration` the module/ADR are named after —
`alembic_version.version_num` is `VARCHAR(32)` (see 0015's own 32-character
revision id, already at that limit) and the fuller name does not fit.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0017_engineering_parameters"
down_revision: Union[str, None] = "0016_gm_zone"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- engineering_parameter --------------------------------------------------
    op.create_table(
        "engineering_parameter",
        sa.Column("parameter_key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("parameter_key"),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"
        ),
    )

    # --- engineering_parameter_audit_log (append-only) --------------------------
    op.create_table(
        "engineering_parameter_audit_log",
        sa.Column("log_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parameter_key", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(
            ["parameter_key"], ["engineering_parameter.parameter_key"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"
        ),
    )
    op.create_index(
        "ix_engineering_parameter_audit_key_time",
        "engineering_parameter_audit_log",
        ["parameter_key", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_engineering_parameter_audit_key_time",
        table_name="engineering_parameter_audit_log",
    )
    op.drop_table("engineering_parameter_audit_log")
    op.drop_table("engineering_parameter")
