"""Stage Setting Registry (ADR-020; ADR-016).

Creates `stage_setting_set`, `stage_setting`, and their own append-only
`stage_setting_registry_audit_log`. See
docs/adr/ADR-020-stage-setting-registry-as-standalone-shared-module.md,
docs/adr/ADR-016-stage-setting-set-as-reusable-versioned-entity.md, and
docs/architecture/stage-setting-set-architecture.md for the full
architecture.

References `user.user_id` (IAM, already exists) and `region.region_id`
(Core Platform reference data, already exists) only — no cross-module
table is altered, and no UFLS/UVLS/EMLS table is created or referenced
(those modules do not exist yet).

Two partial unique indexes on `stage_setting` — not one plain composite
unique constraint — implement "unique `stage_order` per region scope,
including the grid-wide null-scope group treated as its own scope"
(stage-setting-set-architecture.md §7 rule 4) correctly: standard SQL
treats every `NULL` as distinct from every other `NULL` in a uniqueness
check, so a single `UNIQUE(stage_setting_set_id, region_scope_id,
stage_order)` constraint would never actually reject two UFLS rows
(`region_scope_id IS NULL`) sharing the same `stage_order`. See
`app/modules/stage_setting_registry/models.py`'s own docstring for the
full reasoning; mirrors the exact `postgresql_where`/`sqlite_where`
dual-index technique already established for
`automatic_load_shedding_functionality`'s own partial unique indexes
(0014_alsf_registry.py).

Revision id shortened to `0018_stage_setting_registry` (27 characters) —
`alembic_version.version_num` is `VARCHAR(32)`, discovered in Sprint 1
(0017_engineering_parameters, itself shortened from the fuller module
name for the same reason).

Hand-written and manually reviewed, following the same review discipline
as every prior migration in this series — not machine-autogenerated.

Revision ID: 0018_stage_setting_registry
Revises: 0017_engineering_parameters
Create Date: 2026-07-15
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0018_stage_setting_registry"
down_revision: Union[str, None] = "0017_engineering_parameters"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- stage_setting_set --------------------------------------------------------
    op.create_table(
        "stage_setting_set",
        sa.Column("stage_setting_set_id", sa.Uuid(), nullable=False),
        sa.Column("scheme_type", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="DRAFT"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("stage_setting_set_id"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            "scheme_type IN ('UFLS','UVLS')", name="ck_stage_setting_set_scheme_type"
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','ENTERED_IN_ERROR')",
            name="ck_stage_setting_set_status",
        ),
    )
    op.create_index("ix_stage_setting_set_scheme_type", "stage_setting_set", ["scheme_type"])
    op.create_index("ix_stage_setting_set_status", "stage_setting_set", ["status"])

    # --- stage_setting ---------------------------------------------------------
    op.create_table(
        "stage_setting",
        sa.Column("stage_setting_id", sa.Uuid(), nullable=False),
        sa.Column("stage_setting_set_id", sa.Uuid(), nullable=False),
        sa.Column("stage_order", sa.SmallInteger(), nullable=False),
        sa.Column("threshold_value", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("threshold_unit", sa.String(length=10), nullable=False),
        sa.Column("time_delay_ms", sa.Integer(), nullable=False),
        sa.Column("region_scope_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("stage_setting_id"),
        sa.ForeignKeyConstraint(
            ["stage_setting_set_id"],
            ["stage_setting_set.stage_setting_set_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["region_scope_id"], ["region.region_id"], ondelete="RESTRICT"),
        sa.CheckConstraint("time_delay_ms >= 0", name="ck_stage_setting_time_delay_non_negative"),
        sa.CheckConstraint("threshold_value > 0", name="ck_stage_setting_threshold_positive"),
    )
    op.create_index("ix_stage_setting_set", "stage_setting", ["stage_setting_set_id"])
    op.create_index("ix_stage_setting_region_scope", "stage_setting", ["region_scope_id"])
    # See module docstring — two partial unique indexes, not one plain
    # composite unique constraint.
    op.create_index(
        "uq_stage_setting_order_no_scope",
        "stage_setting",
        ["stage_setting_set_id", "stage_order"],
        unique=True,
        postgresql_where=sa.text("region_scope_id IS NULL"),
        sqlite_where=sa.text("region_scope_id IS NULL"),
    )
    op.create_index(
        "uq_stage_setting_order_scoped",
        "stage_setting",
        ["stage_setting_set_id", "region_scope_id", "stage_order"],
        unique=True,
        postgresql_where=sa.text("region_scope_id IS NOT NULL"),
        sqlite_where=sa.text("region_scope_id IS NOT NULL"),
    )

    # --- stage_setting_registry_audit_log (append-only, polymorphic) --------------
    op.create_table(
        "stage_setting_registry_audit_log",
        sa.Column("log_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject_type", sa.String(length=30), nullable=False),
        sa.Column("stage_setting_set_id", sa.Uuid(), nullable=True),
        # Deliberately NOT a foreign key — a removed StageSetting's own
        # audit history must survive its row being physically deleted
        # (module document §8; models.py's own docstring).
        sa.Column("stage_setting_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(
            ["stage_setting_set_id"],
            ["stage_setting_set.stage_setting_set_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            "subject_type IN ('STAGE_SETTING_SET','STAGE_SETTING')",
            name="ck_ssr_audit_subject_type",
        ),
    )
    op.create_index(
        "ix_ssr_audit_set_time",
        "stage_setting_registry_audit_log",
        ["stage_setting_set_id", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index("ix_ssr_audit_set_time", table_name="stage_setting_registry_audit_log")
    op.drop_table("stage_setting_registry_audit_log")

    op.drop_index("uq_stage_setting_order_scoped", table_name="stage_setting")
    op.drop_index("uq_stage_setting_order_no_scope", table_name="stage_setting")
    op.drop_index("ix_stage_setting_region_scope", table_name="stage_setting")
    op.drop_index("ix_stage_setting_set", table_name="stage_setting")
    op.drop_table("stage_setting")

    op.drop_index("ix_stage_setting_set_status", table_name="stage_setting_set")
    op.drop_index("ix_stage_setting_set_scheme_type", table_name="stage_setting_set")
    op.drop_table("stage_setting_set")
