"""Findings and Publication Governance — Policy Layer (ADR-018).

Creates `publication_treatment_policy` and its own append-only
`publication_treatment_policy_audit_log`. See
docs/adr/ADR-018-findings-severity-and-publication-governance-separation.md
and
docs/architecture/findings-and-publication-governance-architecture.md §4,
§4.2, §12 for the full architecture.

Does **not** create `finding` (transient value contract only — module
document §8, never persisted at Draft time), `publication_record`,
`evaluation_cache`, `scheme_version`, `detector`, or `acknowledgement` —
all explicitly out of this sprint's scope.

References `user.user_id` (IAM, already exists) only, and only nullably
(mirrors `0017_engineering_parameters`'s own nullable-actor precedent for
the bootstrap-seed exception) — no cross-module table is altered.

Four partial unique indexes on `publication_treatment_policy` — not one
plain composite `UNIQUE` constraint — implement "at most one policy per
precedence level" correctly: `finding_type`/`scheme_type` are each
independently nullable ("applies regardless of that dimension"), and
standard SQL treats every `NULL` as distinct from every other `NULL`, so
a single composite constraint would silently permit duplicate global
baselines or duplicate overrides. See
`app/modules/findings_publication_governance/models.py`'s own docstring
for the full reasoning; mirrors the exact `postgresql_where`/
`sqlite_where` dual/multi-index technique already established in
`0014_alsf_registry.py` and `0018_stage_setting_registry.py`.

Revision id kept within the `alembic_version.version_num` `VARCHAR(32)`
limit discovered in Sprint 1.

Hand-written and manually reviewed, following the same review discipline
as every prior migration in this series — not machine-autogenerated.

Revision ID: 0019_publication_treatment
Revises: 0018_stage_setting_registry
Create Date: 2026-07-15
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0019_publication_treatment"
down_revision: Union[str, None] = "0018_stage_setting_registry"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SEVERITY_VALUES = "('INFORMATION','ADVISORY','WARNING','CRITICAL')"
_FINDING_TYPE_VALUES = (
    "('MW_TOLERANCE_DEVIATION','ALSF_CAPABILITY_ABSENCE',"
    "'SENSITIVE_CUSTOMER_ASSOCIATION','TOPOLOGY_REGISTRY_CHANGE',"
    "'BOUNDARY_POCKET_STRUCTURAL','BOUNDARY_POCKET_COMPOSITION',"
    "'CROSS_SCHEME_OVERLAP','CRITICAL_INFRASTRUCTURE_PROTECTION')"
)
_SCHEME_TYPE_VALUES = "('UFLS','UVLS','EMLS')"
_TREATMENT_VALUES = "('BLOCK','ALLOW_WITH_ACKNOWLEDGEMENT','ALLOW_WITHOUT_ACKNOWLEDGEMENT')"


def upgrade() -> None:
    # --- publication_treatment_policy ----------------------------------------------
    op.create_table(
        "publication_treatment_policy",
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("finding_type", sa.String(length=50), nullable=True),
        sa.Column("scheme_type", sa.String(length=10), nullable=True),
        sa.Column("treatment", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("policy_id"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            f"severity IN {_SEVERITY_VALUES}", name="ck_publication_policy_severity"
        ),
        sa.CheckConstraint(
            f"finding_type IS NULL OR finding_type IN {_FINDING_TYPE_VALUES}",
            name="ck_publication_policy_finding_type",
        ),
        sa.CheckConstraint(
            f"scheme_type IS NULL OR scheme_type IN {_SCHEME_TYPE_VALUES}",
            name="ck_publication_policy_scheme_type",
        ),
        sa.CheckConstraint(
            f"treatment IN {_TREATMENT_VALUES}", name="ck_publication_policy_treatment"
        ),
    )
    op.create_index("ix_publication_policy_severity", "publication_treatment_policy", ["severity"])
    op.create_index(
        "ix_publication_policy_finding_type", "publication_treatment_policy", ["finding_type"]
    )
    op.create_index(
        "ix_publication_policy_scheme_type", "publication_treatment_policy", ["scheme_type"]
    )
    # Level 4 — global severity baseline: one row per severity.
    op.create_index(
        "uq_publication_policy_baseline",
        "publication_treatment_policy",
        ["severity"],
        unique=True,
        postgresql_where=sa.text("finding_type IS NULL AND scheme_type IS NULL"),
        sqlite_where=sa.text("finding_type IS NULL AND scheme_type IS NULL"),
    )
    # Level 3 — scheme-specific severity override (finding-type-agnostic).
    op.create_index(
        "uq_publication_policy_scheme_severity",
        "publication_treatment_policy",
        ["severity", "scheme_type"],
        unique=True,
        postgresql_where=sa.text("finding_type IS NULL AND scheme_type IS NOT NULL"),
        sqlite_where=sa.text("finding_type IS NULL AND scheme_type IS NOT NULL"),
    )
    # Level 2 — global finding-type override (scheme-agnostic).
    op.create_index(
        "uq_publication_policy_finding_type",
        "publication_treatment_policy",
        ["severity", "finding_type"],
        unique=True,
        postgresql_where=sa.text("finding_type IS NOT NULL AND scheme_type IS NULL"),
        sqlite_where=sa.text("finding_type IS NOT NULL AND scheme_type IS NULL"),
    )
    # Level 1 — scheme-specific + finding-type-specific override (most specific).
    op.create_index(
        "uq_publication_policy_scheme_finding_type",
        "publication_treatment_policy",
        ["severity", "finding_type", "scheme_type"],
        unique=True,
        postgresql_where=sa.text("finding_type IS NOT NULL AND scheme_type IS NOT NULL"),
        sqlite_where=sa.text("finding_type IS NOT NULL AND scheme_type IS NOT NULL"),
    )

    # --- publication_treatment_policy_audit_log (append-only) -----------------------
    op.create_table(
        "publication_treatment_policy_audit_log",
        sa.Column("log_id", sa.Integer(), autoincrement=True, nullable=False),
        # Deliberately NOT a foreign key — a removed override's own audit
        # history must survive its row being physically deleted (module
        # document §11; models.py's own docstring).
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("finding_type", sa.String(length=50), nullable=True),
        sa.Column("scheme_type", sa.String(length=10), nullable=True),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id"),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            "action IN ('created','treatment_changed','removed')",
            name="ck_publication_policy_audit_action",
        ),
    )
    op.create_index(
        "ix_publication_policy_audit_policy_time",
        "publication_treatment_policy_audit_log",
        ["policy_id", sa.text("changed_at DESC")],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_publication_policy_audit_policy_time",
        table_name="publication_treatment_policy_audit_log",
    )
    op.drop_table("publication_treatment_policy_audit_log")

    op.drop_index(
        "uq_publication_policy_scheme_finding_type", table_name="publication_treatment_policy"
    )
    op.drop_index("uq_publication_policy_finding_type", table_name="publication_treatment_policy")
    op.drop_index(
        "uq_publication_policy_scheme_severity", table_name="publication_treatment_policy"
    )
    op.drop_index("uq_publication_policy_baseline", table_name="publication_treatment_policy")
    op.drop_index("ix_publication_policy_scheme_type", table_name="publication_treatment_policy")
    op.drop_index("ix_publication_policy_finding_type", table_name="publication_treatment_policy")
    op.drop_index("ix_publication_policy_severity", table_name="publication_treatment_policy")
    op.drop_table("publication_treatment_policy")
