"""Findings and Publication Governance — Publication Record Foundation
(ADR-018).

Creates `publication_record` (the permanent, immutable evidence of one
completed Publish action) and its three frozen-evidence child tables:
`publication_record_finding`, `publication_record_prerequisite`,
`publication_record_acknowledgement`. See
docs/adr/ADR-018-findings-severity-and-publication-governance-separation.md
and
docs/architecture/findings-and-publication-governance-architecture.md §2,
§2.1, §5, §6, §8 for the full architecture.

Does **not** create `finding` (transient value contract only — never a
table, module document §8), `scheme_version` (no generic shared
SchemeVersion table — this sprint's own instructions §3; a future scheme
module remains the sole owner of its own version table, which does not
exist yet), `detector`, or `evaluation_cache` — all explicitly out of
scope.

`publication_record.scheme_version_id`/`topology_version_id`/
`load_snapshot_id` are deliberately **not** foreign keys — CLAUDE.md
A2/F2's dependency direction means Shared Platform never depends on, and
holds no foreign key into, any scheme module's own tables (which do not
exist yet regardless); these are opaque, unenforced cross-module
identifiers, evidence only. `published_by_user_id`/`changed_by_user_id`/
`acknowledged_by_user_id` all reference `user.user_id` (IAM), which does
exist, and are real (non-nullable — every Publication requires a real,
named, authenticated Administrator, never a system/bootstrap actor)
foreign keys.

`publication_record_acknowledgement` carries a genuine composite foreign
key into `publication_record_finding` (`publication_record_id`,
`finding_index`) — real same-aggregate referential integrity, not a
cross-module reference, ensuring an acknowledgement can only ever
reference a finding that actually exists within the same
`PublicationRecord`.

Concurrency / duplicate-publication-event prevention (this sprint's own
instructions §12): `publication_record.publication_event_id` carries a
database-level `UNIQUE` constraint — the caller-supplied idempotency key
this sprint's own service layer (`service.py`) rejects a duplicate
against, before any other work, on every publish attempt.

Revision id kept within the `alembic_version.version_num` `VARCHAR(32)`
limit discovered in Sprint 1.

Hand-written and manually reviewed, following the same review discipline
as every prior migration in this series — not machine-autogenerated.

Revision ID: 0020_publication_record
Revises: 0019_publication_treatment
Create Date: 2026-07-15
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0020_publication_record"
down_revision: Union[str, None] = "0019_publication_treatment"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEME_TYPE_VALUES = "('UFLS','UVLS','EMLS')"
_SEVERITY_VALUES = "('INFORMATION','ADVISORY','WARNING','CRITICAL')"
_FINDING_TYPE_VALUES = (
    "('MW_TOLERANCE_DEVIATION','ALSF_CAPABILITY_ABSENCE',"
    "'SENSITIVE_CUSTOMER_ASSOCIATION','TOPOLOGY_REGISTRY_CHANGE',"
    "'BOUNDARY_POCKET_STRUCTURAL','BOUNDARY_POCKET_COMPOSITION',"
    "'CROSS_SCHEME_OVERLAP','CRITICAL_INFRASTRUCTURE_PROTECTION')"
)
_TREATMENT_VALUES = "('BLOCK','ALLOW_WITH_ACKNOWLEDGEMENT','ALLOW_WITHOUT_ACKNOWLEDGEMENT')"

# JSONB on PostgreSQL, plain JSON elsewhere — mirrors
# `0012_psse_integration.py`'s own established portable-JSON precedent.
_json_type = sa.JSON().with_variant(JSONB(), "postgresql")


def upgrade() -> None:
    # --- publication_record (immutable, one row per completed Publish) -------------
    op.create_table(
        "publication_record",
        sa.Column("publication_record_id", sa.Uuid(), nullable=False),
        sa.Column("publication_event_id", sa.Uuid(), nullable=False),
        sa.Column("scheme_type", sa.String(length=10), nullable=False),
        sa.Column("scheme_version_id", sa.Uuid(), nullable=False),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "published_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("topology_version_id", sa.Uuid(), nullable=True),
        sa.Column("load_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("evidence_schema_version", sa.Integer(), nullable=False, server_default="1"),
        sa.PrimaryKeyConstraint("publication_record_id"),
        sa.ForeignKeyConstraint(["published_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            f"scheme_type IN {_SCHEME_TYPE_VALUES}", name="ck_publication_record_scheme_type"
        ),
    )
    op.create_index(
        "uq_publication_record_event", "publication_record", ["publication_event_id"], unique=True
    )
    op.create_index("ix_publication_record_scheme_type", "publication_record", ["scheme_type"])
    op.create_index(
        "ix_publication_record_scheme_version", "publication_record", ["scheme_version_id"]
    )
    op.create_index("ix_publication_record_published_at", "publication_record", ["published_at"])

    # --- publication_record_finding (frozen Finding + resolved treatment) -----------
    op.create_table(
        "publication_record_finding",
        sa.Column("publication_record_finding_id", sa.Uuid(), nullable=False),
        sa.Column("publication_record_id", sa.Uuid(), nullable=False),
        sa.Column("finding_index", sa.SmallInteger(), nullable=False),
        sa.Column("finding_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_object_type", sa.String(length=100), nullable=False),
        sa.Column("affected_object_id", sa.String(length=200), nullable=False),
        sa.Column("evidence", _json_type, nullable=True),
        sa.Column("resolved_treatment", sa.String(length=40), nullable=False),
        sa.Column("matched_policy_id", sa.Uuid(), nullable=True),
        sa.Column("matched_policy_severity", sa.String(length=20), nullable=False),
        sa.Column("matched_policy_finding_type", sa.String(length=50), nullable=True),
        sa.Column("matched_policy_scheme_type", sa.String(length=10), nullable=True),
        sa.Column("acknowledgement_required", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("publication_record_finding_id"),
        sa.ForeignKeyConstraint(
            ["publication_record_id"],
            ["publication_record.publication_record_id"],
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"finding_type IN {_FINDING_TYPE_VALUES}", name="ck_publication_record_finding_type"
        ),
        sa.CheckConstraint(
            f"severity IN {_SEVERITY_VALUES}", name="ck_publication_record_finding_severity"
        ),
        sa.CheckConstraint(
            f"resolved_treatment IN {_TREATMENT_VALUES}",
            name="ck_publication_record_finding_treatment",
        ),
        sa.CheckConstraint(
            f"matched_policy_severity IN {_SEVERITY_VALUES}",
            name="ck_publication_record_finding_matched_severity",
        ),
    )
    op.create_index(
        "uq_publication_record_finding_index",
        "publication_record_finding",
        ["publication_record_id", "finding_index"],
        unique=True,
    )
    op.create_index(
        "ix_publication_record_finding_record",
        "publication_record_finding",
        ["publication_record_id"],
    )

    # --- publication_record_prerequisite (frozen prerequisite results) --------------
    op.create_table(
        "publication_record_prerequisite",
        sa.Column("publication_record_prerequisite_id", sa.Uuid(), nullable=False),
        sa.Column("publication_record_id", sa.Uuid(), nullable=False),
        sa.Column("prerequisite_index", sa.SmallInteger(), nullable=False),
        sa.Column("prerequisite_code", sa.String(length=100), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_object_type", sa.String(length=100), nullable=True),
        sa.Column("affected_object_id", sa.String(length=200), nullable=True),
        sa.Column("evidence", _json_type, nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("publication_record_prerequisite_id"),
        sa.ForeignKeyConstraint(
            ["publication_record_id"],
            ["publication_record.publication_record_id"],
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "uq_publication_record_prerequisite_index",
        "publication_record_prerequisite",
        ["publication_record_id", "prerequisite_index"],
        unique=True,
    )
    op.create_index(
        "ix_publication_record_prerequisite_record",
        "publication_record_prerequisite",
        ["publication_record_id"],
    )

    # --- publication_record_acknowledgement (frozen acknowledgement evidence) -------
    op.create_table(
        "publication_record_acknowledgement",
        sa.Column("publication_record_acknowledgement_id", sa.Uuid(), nullable=False),
        sa.Column("publication_record_id", sa.Uuid(), nullable=False),
        sa.Column("finding_index", sa.SmallInteger(), nullable=False),
        sa.Column("acknowledged_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "acknowledged_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("publication_record_acknowledgement_id"),
        sa.ForeignKeyConstraint(
            ["publication_record_id"],
            ["publication_record.publication_record_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["acknowledged_by_user_id"], ["user.user_id"], ondelete="RESTRICT"),
        # Genuine same-aggregate referential integrity — see module
        # docstring: an acknowledgement can only reference a finding that
        # actually exists within this same PublicationRecord.
        sa.ForeignKeyConstraint(
            ["publication_record_id", "finding_index"],
            [
                "publication_record_finding.publication_record_id",
                "publication_record_finding.finding_index",
            ],
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "uq_publication_record_ack_finding",
        "publication_record_acknowledgement",
        ["publication_record_id", "finding_index"],
        unique=True,
    )
    op.create_index(
        "ix_publication_record_ack_record",
        "publication_record_acknowledgement",
        ["publication_record_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_publication_record_ack_record", table_name="publication_record_acknowledgement"
    )
    op.drop_index(
        "uq_publication_record_ack_finding", table_name="publication_record_acknowledgement"
    )
    op.drop_table("publication_record_acknowledgement")

    op.drop_index(
        "ix_publication_record_prerequisite_record", table_name="publication_record_prerequisite"
    )
    op.drop_index(
        "uq_publication_record_prerequisite_index", table_name="publication_record_prerequisite"
    )
    op.drop_table("publication_record_prerequisite")

    op.drop_index("ix_publication_record_finding_record", table_name="publication_record_finding")
    op.drop_index("uq_publication_record_finding_index", table_name="publication_record_finding")
    op.drop_table("publication_record_finding")

    op.drop_index("ix_publication_record_published_at", table_name="publication_record")
    op.drop_index("ix_publication_record_scheme_version", table_name="publication_record")
    op.drop_index("ix_publication_record_scheme_type", table_name="publication_record")
    op.drop_index("uq_publication_record_event", table_name="publication_record")
    op.drop_table("publication_record")
