"""Stage Setting Trigger (ADR-025).

A shedding stage may carry more than one independent frequency/voltage-time
operating criterion (e.g. a fast, low-delay trip and a slower backup trip
protecting the same stage) — the as-built one-threshold-per-stage model
could not represent this real site configuration. See
docs/adr/ADR-025-stage-setting-trigger-multiple-operating-criteria.md and
docs/architecture/stage-setting-set-architecture.md for the full
architecture.

This migration:

1. Creates `stage_setting_trigger` — one row per independent operating
   criterion, owned by exactly one `stage_setting` (the stage).
2. Backfills exactly one trigger (`trigger_order = 1`) from every existing
   `stage_setting` row's own `threshold_value`/`threshold_unit`/
   `time_delay_ms`, preserving the row's existing values exactly.
3. Drops `threshold_value`, `threshold_unit`, and `time_delay_ms` from
   `stage_setting` — the values now live exclusively on
   `stage_setting_trigger` (CLAUDE.md §5.1: no two authoritative copies of
   the same engineering value; ADR-025's own "Alternatives Considered"
   explicitly rejects retaining these as deprecated compatibility columns).
4. Extends `stage_setting_registry_audit_log`'s own `subject_type` CHECK
   constraint to also accept `'STAGE_SETTING_TRIGGER'`, and adds a
   deliberately-not-a-foreign-key `stage_setting_trigger_id` column,
   mirroring `stage_setting_id`'s own existing treatment on that table
   (see `models.py`'s own docstring for why).

No `StageSettingSet`, `StageSetting`, or `UflsStage.stage_setting_id` row
is deleted, recreated, or reassigned a new identity by this migration —
every stage keeps its own `stage_setting_id`, so every existing UFLS
reference (and every existing Published Stage Setting Set) remains valid
without modification.

Hand-written and manually reviewed, following the same review discipline
as every prior migration in this series — not machine-autogenerated. Does
not edit `0018_stage_setting_registry` in place (CLAUDE.md's own
established convention — never edit a previously-shipped migration); this
is an additive, then backfilling-then-cleanup, correction on top of it.

Revision ID: 0025_stage_setting_trigger
Revises: 0024_ssr_audit_fk_correction
Create Date: 2026-07-17
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0025_stage_setting_trigger"
down_revision: Union[str, None] = "0024_ssr_audit_fk_correction"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- 1. Create stage_setting_trigger ----------------------------------------
    op.create_table(
        "stage_setting_trigger",
        sa.Column("stage_setting_trigger_id", sa.Uuid(), nullable=False),
        sa.Column("stage_setting_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_order", sa.SmallInteger(), nullable=False),
        sa.Column("threshold_value", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("threshold_unit", sa.String(length=10), nullable=False),
        sa.Column("time_delay_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("stage_setting_trigger_id"),
        sa.ForeignKeyConstraint(
            ["stage_setting_id"], ["stage_setting.stage_setting_id"], ondelete="RESTRICT"
        ),
        sa.CheckConstraint(
            "time_delay_ms >= 0", name="ck_stage_setting_trigger_time_delay_non_negative"
        ),
        sa.CheckConstraint(
            "threshold_value > 0", name="ck_stage_setting_trigger_threshold_positive"
        ),
    )
    op.create_index(
        "uq_stage_setting_trigger_order",
        "stage_setting_trigger",
        ["stage_setting_id", "trigger_order"],
        unique=True,
    )
    op.create_index(
        "uq_stage_setting_trigger_pair",
        "stage_setting_trigger",
        ["stage_setting_id", "threshold_value", "time_delay_ms"],
        unique=True,
    )
    op.create_index("ix_stage_setting_trigger_stage", "stage_setting_trigger", ["stage_setting_id"])

    # --- 2. Backfill: one trigger per existing stage_setting row ----------------
    op.execute(
        """
        INSERT INTO stage_setting_trigger
            (stage_setting_trigger_id, stage_setting_id, trigger_order,
             threshold_value, threshold_unit, time_delay_ms)
        SELECT
            {uuid_gen}, stage_setting_id, 1,
            threshold_value, threshold_unit, time_delay_ms
        FROM stage_setting
        """.format(
            uuid_gen=(
                "gen_random_uuid()"
                if op.get_bind().dialect.name == "postgresql"
                else "lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || "
                "substr(lower(hex(randomblob(2))),2) || '-' || "
                "substr('89ab',abs(random()) % 4 + 1, 1) || "
                "substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))"
            )
        )
    )

    # --- 3. Drop the now-superseded columns from stage_setting -------------------
    # SQLite has no native DROP COLUMN before 3.35; batch mode handles both
    # dialects uniformly, mirroring this project's other structural
    # SQLite-compatible migrations.
    with op.batch_alter_table("stage_setting") as batch_op:
        batch_op.drop_constraint("ck_stage_setting_time_delay_non_negative", type_="check")
        batch_op.drop_constraint("ck_stage_setting_threshold_positive", type_="check")
        batch_op.drop_column("threshold_value")
        batch_op.drop_column("threshold_unit")
        batch_op.drop_column("time_delay_ms")

    # --- 4. Extend the audit log for the new subject type ------------------------
    with op.batch_alter_table("stage_setting_registry_audit_log") as batch_op:
        batch_op.add_column(sa.Column("stage_setting_trigger_id", sa.Uuid(), nullable=True))
        batch_op.drop_constraint("ck_ssr_audit_subject_type", type_="check")
        batch_op.create_check_constraint(
            "ck_ssr_audit_subject_type",
            "subject_type IN ('STAGE_SETTING_SET','STAGE_SETTING','STAGE_SETTING_TRIGGER')",
        )


def downgrade() -> None:
    with op.batch_alter_table("stage_setting_registry_audit_log") as batch_op:
        batch_op.drop_constraint("ck_ssr_audit_subject_type", type_="check")
        batch_op.create_check_constraint(
            "ck_ssr_audit_subject_type",
            "subject_type IN ('STAGE_SETTING_SET','STAGE_SETTING')",
        )
        batch_op.drop_column("stage_setting_trigger_id")

    with op.batch_alter_table("stage_setting") as batch_op:
        batch_op.add_column(sa.Column("threshold_value", sa.Numeric(precision=9, scale=4)))
        batch_op.add_column(sa.Column("threshold_unit", sa.String(length=10)))
        batch_op.add_column(sa.Column("time_delay_ms", sa.Integer()))

    # Backfill from each stage's own trigger_order = 1 row (the same row
    # `upgrade()` created from it, if this stage was never given a second
    # trigger; if it was, this recovers only the original single value —
    # any additional trigger added after this migration shipped is, by
    # definition, data this downgrade path cannot represent and is
    # discarded, exactly as any other lossy downgrade in this series).
    op.execute(
        """
        UPDATE stage_setting
        SET threshold_value = t.threshold_value,
            threshold_unit = t.threshold_unit,
            time_delay_ms = t.time_delay_ms
        FROM stage_setting_trigger t
        WHERE t.stage_setting_id = stage_setting.stage_setting_id
          AND t.trigger_order = 1
        """
        if op.get_bind().dialect.name == "postgresql"
        else """
        UPDATE stage_setting
        SET threshold_value = (
                SELECT t.threshold_value FROM stage_setting_trigger t
                WHERE t.stage_setting_id = stage_setting.stage_setting_id
                  AND t.trigger_order = 1
            ),
            threshold_unit = (
                SELECT t.threshold_unit FROM stage_setting_trigger t
                WHERE t.stage_setting_id = stage_setting.stage_setting_id
                  AND t.trigger_order = 1
            ),
            time_delay_ms = (
                SELECT t.time_delay_ms FROM stage_setting_trigger t
                WHERE t.stage_setting_id = stage_setting.stage_setting_id
                  AND t.trigger_order = 1
            )
        """
    )

    with op.batch_alter_table("stage_setting") as batch_op:
        batch_op.alter_column("threshold_value", nullable=False)
        batch_op.alter_column("threshold_unit", nullable=False)
        batch_op.alter_column("time_delay_ms", nullable=False)
        batch_op.create_check_constraint(
            "ck_stage_setting_time_delay_non_negative", "time_delay_ms >= 0"
        )
        batch_op.create_check_constraint(
            "ck_stage_setting_threshold_positive", "threshold_value > 0"
        )

    op.drop_index("ix_stage_setting_trigger_stage", table_name="stage_setting_trigger")
    op.drop_index("uq_stage_setting_trigger_pair", table_name="stage_setting_trigger")
    op.drop_index("uq_stage_setting_trigger_order", table_name="stage_setting_trigger")
    op.drop_table("stage_setting_trigger")
